### PR TITLE
About Me

### LINKED ISSUE #6: About Us
image

### PR DESCRIPTION
**Pull request by KarGitH**

### CODE REVIEW

**Review by arpitBhalla — CHANGES_REQUESTED** [review]
Make it responsive

**Review by mehul-2000 — CHANGES_REQUESTED** [review]
Make the page responsive, design and styling is ok.

**Comment by KarGitH** [comment]
Sir , i have done changes in my code if it will automatically change here or I have to do something

**Review by mehul-2000 — APPROVED** [review]
OK

**Pull request closed without merging**
